INCLUDE ../globals.ink
~Dragon=3
W-we won...#speaker: Gary #portrait: Gary_neutral  #audio: GaryAudio
He's dead...
For once... I actually defeated something...
I was so scared...
<i>Thank you...</i>
<i>Thank you for believing in me, Hero.</i>
...
Wait, I just remembered, how dare you look at your teacher like that you horrid disciple!
Oh, looks like he dropped something.
Let's go see what it is!
->END